### ISSUE TITLE
[FEATURE] Add README.md

### ISSUE THREAD

**Issue by ShorunTech** [CryptoverseWeb3/Community.CryptoverseWeb3#15] opened 2022-10-01 20:07 UTC
### Detailed description

![Screenshot (148)](https://user-images.githubusercontent.com/61280687/193426413-4ae4e3ad-5605-4701-8e1f-5fade49f753c.png)

### Context

-- Make it Easy for me to run the Website
--Run it Locally
--Easy for new contributors to navigate on the website

### Possible implementation

you can take an example from this repository
https://github.com/thecyberworld/thecyberhub.org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShorunTech** [comment] 2022-10-01 20:10
Can this issue be assign to me

**Comment by 0xk4b1r** [comment] 2022-10-02 15:52
duplicate of #11

**Comment by 0xk4b1r** [comment] 2022-10-14 10:52
@ShorunTech

**Comment by ShorunTech** [comment] 2022-10-14 11:07
Ok

**Comment by 0xk4b1r** [comment] 2022-10-14 11:18
> Ok

you can do this from here
https://github.com/thecyberworld/thecyberhub.org
same reademe file 
just change the name

**Comment by ShorunTech** [comment] 2022-10-14 11:19
Thank you for that.

**Closed as completed** 2022-10-19 04:19 UTC
Labels: good first issue, 🟥 priority: critical, hacktoberfest, ⭐ goal: addition, 🤩 status : Up for Grab, 📄 aspect: text
